### ISSUE TITLE
Auslesen von packData

### ISSUE THREAD

**Issue by wurbar** [surfer1264/Zendure-Stuff#4]
Lieber Jörg, wir hatten Kontakt über das Zendure Forum. Ich habe zwischenzeitlich den mqtt broker nochmals aufgesetzt und auch das mqtt.yaml und das configuration.yaml so wie vorgegeben erstellt. Im homeassistant kann ich die sensoren minVol und maxVol (ich habe nur diese im mqtt.yaml aufgesetzt) sehen, ihre Werte sind aber „unbekannt“. Im Logbuch erscheinen die Werte unter packdata und für die beiden AB2000. Ich komme leider nicht mehr weiter. Ich sehe keine packdata-Leichen und habe sowohl packdata.minVol als auch packData[0].minVol probiert. Was müsste ich Dir an Unterlagen zusätzlich noch zustellen? Herzlichen Dank für Deine Unterstützung. Walter

**Comment by surfer1264** [comment]
Hallo Walter,
schreibe mir mal unter 
surfer1264@bkw.jihlefeld.de mit Antworten und Anhängen und Screenshots

Aktuell habe ich noch keine Idee, aber ich möchte hier keine Config-Daten mit Dir austauschen
1.) Sind alle YAML-Files valide in Deinem HA?
=> siehe Entwicklerwerkzeuge => Konfiguration prüfen
=> siehe Entwicklerwerkzeuge => manuell konfigurierte MQTT - Entitäten prüfen
2.) Geräte& Dienste => MQTT
Dort müsste es 1 Gerät geben
SmartPV Hub 1200 Controller
mit 2 Werten
sensor.solarflow_batterie_1_maxvol
sensor.solarflow_batterie_1_minvol
und beide sind aktiviert?

Nebenbei gesagt....auch bei mir sind die Sensoren auf unbekannt (ist gerade dunkel, und der Hub ist aus.....da gibt es dann keine MQTT-Daten)

Im MQTT Bereich muss es auch den
sensor.packdata geben 
und ist aktiviert?

Im Logbuch findest DU dann auch? 
packData geändert zu [{'maxVol': 328, 'sn': 'XXXXXXXXXXXXXXXXX'}]

3.) 
Schicke mir mal Deine configuration.yaml. zu (as is)
Schicke mir mal Deine mqtt.yaml. zu (as is)
In welchem Pfad liegt die mqtt.yaml?

4.)
In Add-Ins => Mosquitto Broker => Protokoll gibt es keine Fehler?
der Broker ist gestartet, richtig?

Grüße Jörg
Kann dauern...bis ich antworte

**Comment by surfer1264** [comment]
mqtt.yaml muss so aussehen: kannst DU hier prüfen
https://jsonformatter.org/yaml-validator

```
sensor:
    - name: Batterie 1 minVol
      unique_id: <deviceID>Batterie1minVol
      state_topic: <appKey>/<deviceID>/state
      value_template: '{{ value_json.packData[0].minVol | float / 100 }}'
      unit_of_measurement: "V"
      device_class: voltage
      device: 
        name: SolarFlow
        identifiers: <EurePVHubSeriennummer>
        manufacturer: Zendure
        model: SmartPV Hub 1200 Controller
```
